# Generated by Django 4.2.4 on 2023-09-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('opening_hours', models.CharField(max_length=10)),
                ('closing_hours', models.CharField(max_length=10)),
            ],
        ),
    ]
